<?php

namespace Database\Seeders;

use App\Models\Permission;
use Illuminate\Database\Seeder;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permissions = [
            // User Management Permissions
            [
                'title_ru' => 'Просмотр пользователей',
                'title_kk' => 'Пайдаланушыларды көру',
                'title_en' => 'View Users',
                'description_ru' => 'Разрешение на просмотр списка пользователей системы',
                'description_kk' => 'Жүйе пайдаланушыларының тізімін көру рұқсаты',
                'description_en' => 'Permission to view system users list',
                'value' => 'view-users',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Создание пользователей',
                'title_kk' => 'Пайдаланушыларды жасау',
                'title_en' => 'Create Users',
                'description_ru' => 'Разрешение на создание новых пользователей системы',
                'description_kk' => 'Жүйеде жаңа пайдаланушыларды жасау рұқсаты',
                'description_en' => 'Permission to create new system users',
                'value' => 'create-users',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Управление пользователями',
                'title_kk' => 'Пайдаланушыларды басқару',
                'title_en' => 'Manage Users',
                'description_ru' => 'Разрешение на редактирование существующих пользователей',
                'description_kk' => 'Қолданыстағы пайдаланушыларды өңдеу рұқсаты',
                'description_en' => 'Permission to edit existing users',
                'value' => 'manage-users',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Удаление пользователей',
                'title_kk' => 'Пайдаланушыларды жою',
                'title_en' => 'Delete Users',
                'description_ru' => 'Разрешение на удаление пользователей системы',
                'description_kk' => 'Жүйе пайдаланушыларын жою рұқсаты',
                'description_en' => 'Permission to delete system users',
                'value' => 'delete-users',
                'is_system' => true,
            ],

            // Role Management Permissions
            [
                'title_ru' => 'Просмотр ролей',
                'title_kk' => 'Рөлдерді көру',
                'title_en' => 'View Roles',
                'description_ru' => 'Разрешение на просмотр списка ролей системы',
                'description_kk' => 'Жүйе рөлдерінің тізімін көру рұқсаты',
                'description_en' => 'Permission to view system roles list',
                'value' => 'view-roles',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Создание ролей',
                'title_kk' => 'Рөлдерді жасау',
                'title_en' => 'Create Roles',
                'description_ru' => 'Разрешение на создание новых ролей системы',
                'description_kk' => 'Жүйеде жаңа рөлдерді жасау рұқсаты',
                'description_en' => 'Permission to create new system roles',
                'value' => 'create-roles',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Управление ролями',
                'title_kk' => 'Рөлдерді басқару',
                'title_en' => 'Manage Roles',
                'description_ru' => 'Разрешение на редактирование существующих ролей',
                'description_kk' => 'Қолданыстағы рөлдерді өңдеу рұқсаты',
                'description_en' => 'Permission to edit existing roles',
                'value' => 'manage-roles',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Удаление ролей',
                'title_kk' => 'Рөлдерді жою',
                'title_en' => 'Delete Roles',
                'description_ru' => 'Разрешение на удаление ролей системы',
                'description_kk' => 'Жүйе рөлдерін жою рұқсаты',
                'description_en' => 'Permission to delete system roles',
                'value' => 'delete-roles',
                'is_system' => true,
            ],

            // Permission Management Permissions
            [
                'title_ru' => 'Просмотр прав',
                'title_kk' => 'Құқықтарды көру',
                'title_en' => 'View Permissions',
                'description_ru' => 'Разрешение на просмотр списка прав доступа',
                'description_kk' => 'Қатынау құқықтарының тізімін көру рұқсаты',
                'description_en' => 'Permission to view permissions list',
                'value' => 'view-permissions',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Создание прав',
                'title_kk' => 'Құқықтарды жасау',
                'title_en' => 'Create Permissions',
                'description_ru' => 'Разрешение на создание новых прав доступа',
                'description_kk' => 'Жаңа қатынау құқықтарын жасау рұқсаты',
                'description_en' => 'Permission to create new permissions',
                'value' => 'create-permissions',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Управление правами',
                'title_kk' => 'Құқықтарды басқару',
                'title_en' => 'Manage Permissions',
                'description_ru' => 'Разрешение на редактирование существующих прав доступа',
                'description_kk' => 'Қолданыстағы қатынау құқықтарын өңдеу рұқсаты',
                'description_en' => 'Permission to edit existing permissions',
                'value' => 'manage-permissions',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Удаление прав',
                'title_kk' => 'Құқықтарды жою',
                'title_en' => 'Delete Permissions',
                'description_ru' => 'Разрешение на удаление прав доступа',
                'description_kk' => 'Қатынау құқықтарын жою рұқсаты',
                'description_en' => 'Permission to delete permissions',
                'value' => 'delete-permissions',
                'is_system' => true,
            ],

            // Season Management Permissions
            [
                'title_ru' => 'Просмотр сезонов',
                'title_kk' => 'Маусымдарды көру',
                'title_en' => 'View Seasons',
                'description_ru' => 'Разрешение на просмотр списка сезонов',
                'description_kk' => 'Маусымдар тізімін көру рұқсаты',
                'description_en' => 'Permission to view seasons list',
                'value' => 'view-seasons',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Создание сезонов',
                'title_kk' => 'Маусымдарды жасау',
                'title_en' => 'Create Seasons',
                'description_ru' => 'Разрешение на создание новых сезонов',
                'description_kk' => 'Жаңа маусымдарды жасау рұқсаты',
                'description_en' => 'Permission to create new seasons',
                'value' => 'create-seasons',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Управление сезонами',
                'title_kk' => 'Маусымдарды басқару',
                'title_en' => 'Manage Seasons',
                'description_ru' => 'Разрешение на редактирование существующих сезонов',
                'description_kk' => 'Қолданыстағы маусымдарды өңдеу рұқсаты',
                'description_en' => 'Permission to edit existing seasons',
                'value' => 'manage-seasons',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Удаление сезонов',
                'title_kk' => 'Маусымдарды жою',
                'title_en' => 'Delete Seasons',
                'description_ru' => 'Разрешение на удаление сезонов',
                'description_kk' => 'Маусымдарды жою рұқсаты',
                'description_en' => 'Permission to delete seasons',
                'value' => 'delete-seasons',
                'is_system' => true,
            ],

            // Category Document Management Permissions
            [
                'title_ru' => 'Просмотр категорий документов',
                'title_kk' => 'Құжат санаттарын көру',
                'title_en' => 'View Category Documents',
                'description_ru' => 'Разрешение на просмотр списка категорий документов',
                'description_kk' => 'Құжат санаттарының тізімін көру рұқсаты',
                'description_en' => 'Permission to view category documents list',
                'value' => 'view-category-documents',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Создание категорий документов',
                'title_kk' => 'Құжат санаттарын жасау',
                'title_en' => 'Create Category Documents',
                'description_ru' => 'Разрешение на создание новых категорий документов',
                'description_kk' => 'Жаңа құжат санаттарын жасау рұқсаты',
                'description_en' => 'Permission to create new category documents',
                'value' => 'create-category-documents',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Управление категориями документов',
                'title_kk' => 'Құжат санаттарын басқару',
                'title_en' => 'Manage Category Documents',
                'description_ru' => 'Разрешение на редактирование существующих категорий документов',
                'description_kk' => 'Қолданыстағы құжат санаттарын өңдеу рұқсаты',
                'description_en' => 'Permission to edit existing category documents',
                'value' => 'manage-category-documents',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Удаление категорий документов',
                'title_kk' => 'Құжат санаттарын жою',
                'title_en' => 'Delete Category Documents',
                'description_ru' => 'Разрешение на удаление категорий документов',
                'description_kk' => 'Құжат санаттарын жою рұқсаты',
                'description_en' => 'Permission to delete category documents',
                'value' => 'delete-category-documents',
                'is_system' => true,
            ],

            // Document Management Permissions
            [
                'title_ru' => 'Просмотр документов',
                'title_kk' => 'Құжаттарды көру',
                'title_en' => 'View Documents',
                'description_ru' => 'Разрешение на просмотр списка документов',
                'description_kk' => 'Құжаттар тізімін көру рұқсаты',
                'description_en' => 'Permission to view documents list',
                'value' => 'view-documents',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Создание документов',
                'title_kk' => 'Құжаттарды жасау',
                'title_en' => 'Create Documents',
                'description_ru' => 'Разрешение на создание новых документов',
                'description_kk' => 'Жаңа құжаттарды жасау рұқсаты',
                'description_en' => 'Permission to create new documents',
                'value' => 'create-documents',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Управление документами',
                'title_kk' => 'Құжаттарды басқару',
                'title_en' => 'Manage Documents',
                'description_ru' => 'Разрешение на редактирование существующих документов',
                'description_kk' => 'Қолданыстағы құжаттарды өңдеу рұқсаты',
                'description_en' => 'Permission to edit existing documents',
                'value' => 'manage-documents',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Удаление документов',
                'title_kk' => 'Құжаттарды жою',
                'title_en' => 'Delete Documents',
                'description_ru' => 'Разрешение на удаление документов',
                'description_kk' => 'Құжаттарды жою рұқсаты',
                'description_en' => 'Permission to delete documents',
                'value' => 'delete-documents',
                'is_system' => true,
            ],

            // Application Status Category Management Permissions
            [
                'title_ru' => 'Просмотр категорий статусов заявок',
                'title_kk' => 'Өтінім мәртебесінің санаттарын көру',
                'title_en' => 'View Application Status Categories',
                'description_ru' => 'Разрешение на просмотр списка категорий статусов заявок',
                'description_kk' => 'Өтінім мәртебесінің санаттар тізімін көру рұқсаты',
                'description_en' => 'Permission to view application status categories list',
                'value' => 'view-application-status-categories',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Создание категорий статусов заявок',
                'title_kk' => 'Өтінім мәртебесінің санаттарын жасау',
                'title_en' => 'Create Application Status Categories',
                'description_ru' => 'Разрешение на создание новых категорий статусов заявок',
                'description_kk' => 'Жаңа өтінім мәртебесінің санаттарын жасау рұқсаты',
                'description_en' => 'Permission to create new application status categories',
                'value' => 'create-application-status-categories',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Управление категориями статусов заявок',
                'title_kk' => 'Өтінім мәртебесінің санаттарын басқару',
                'title_en' => 'Manage Application Status Categories',
                'description_ru' => 'Разрешение на редактирование существующих категорий статусов заявок',
                'description_kk' => 'Қолданыстағы өтінім мәртебесінің санаттарын өңдеу рұқсаты',
                'description_en' => 'Permission to edit existing application status categories',
                'value' => 'manage-application-status-categories',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Удаление категорий статусов заявок',
                'title_kk' => 'Өтінім мәртебесінің санаттарын жою',
                'title_en' => 'Delete Application Status Categories',
                'description_ru' => 'Разрешение на удаление категорий статусов заявок',
                'description_kk' => 'Өтінім мәртебесінің санаттарын жою рұқсаты',
                'description_en' => 'Permission to delete application status categories',
                'value' => 'delete-application-status-categories',
                'is_system' => true,
            ],

            // Application Status Management Permissions
            [
                'title_ru' => 'Просмотр статусов заявок',
                'title_kk' => 'Өтінім мәртебелерін көру',
                'title_en' => 'View Application Statuses',
                'description_ru' => 'Разрешение на просмотр списка статусов заявок',
                'description_kk' => 'Өтінім мәртебелер тізімін көру рұқсаты',
                'description_en' => 'Permission to view application statuses list',
                'value' => 'view-application-statuses',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Создание статусов заявок',
                'title_kk' => 'Өтінім мәртебелерін жасау',
                'title_en' => 'Create Application Statuses',
                'description_ru' => 'Разрешение на создание новых статусов заявок',
                'description_kk' => 'Жаңа өтінім мәртебелерін жасау рұқсаты',
                'description_en' => 'Permission to create new application statuses',
                'value' => 'create-application-statuses',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Управление статусами заявок',
                'title_kk' => 'Өтінім мәртебелерін басқару',
                'title_en' => 'Manage Application Statuses',
                'description_ru' => 'Разрешение на редактирование существующих статусов заявок',
                'description_kk' => 'Қолданыстағы өтінім мәртебелерін өңдеу рұқсаты',
                'description_en' => 'Permission to edit existing application statuses',
                'value' => 'manage-application-statuses',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Удаление статусов заявок',
                'title_kk' => 'Өтінім мәртебелерін жою',
                'title_en' => 'Delete Application Statuses',
                'description_ru' => 'Разрешение на удаление статусов заявок',
                'description_kk' => 'Өтінім мәртебелерін жою рұқсаты',
                'description_en' => 'Permission to delete application statuses',
                'value' => 'delete-application-statuses',
                'is_system' => true,
            ],

            // League Management Permissions
            [
                'title_ru' => 'Просмотр лиг',
                'title_kk' => 'Лигаларды көру',
                'title_en' => 'View Leagues',
                'description_ru' => 'Разрешение на просмотр списка лиг',
                'description_kk' => 'Лигалар тізімін көру рұқсаты',
                'description_en' => 'Permission to view leagues list',
                'value' => 'view-leagues',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Создание лиг',
                'title_kk' => 'Лигаларды жасау',
                'title_en' => 'Create Leagues',
                'description_ru' => 'Разрешение на создание новых лиг',
                'description_kk' => 'Жаңа лигаларды жасау рұқсаты',
                'description_en' => 'Permission to create new leagues',
                'value' => 'create-leagues',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Управление лигами',
                'title_kk' => 'Лигаларды басқару',
                'title_en' => 'Manage Leagues',
                'description_ru' => 'Разрешение на редактирование существующих лиг',
                'description_kk' => 'Қолданыстағы лигаларды өңдеу рұқсаты',
                'description_en' => 'Permission to edit existing leagues',
                'value' => 'manage-leagues',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Удаление лиг',
                'title_kk' => 'Лигаларды жою',
                'title_en' => 'Delete Leagues',
                'description_ru' => 'Разрешение на удаление лиг',
                'description_kk' => 'Лигаларды жою рұқсаты',
                'description_en' => 'Permission to delete leagues',
                'value' => 'delete-leagues',
                'is_system' => true,
            ],

            // Club Management Permissions
            [
                'title_ru' => 'Просмотр клубов',
                'title_kk' => 'Клубтарды көру',
                'title_en' => 'View Clubs',
                'description_ru' => 'Разрешение на просмотр списка клубов',
                'description_kk' => 'Клубтар тізімін көру рұқсаты',
                'description_en' => 'Permission to view clubs list',
                'value' => 'view-clubs',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Создание клубов',
                'title_kk' => 'Клубтарды жасау',
                'title_en' => 'Create Clubs',
                'description_ru' => 'Разрешение на создание новых клубов',
                'description_kk' => 'Жаңа клубтарды жасау рұқсаты',
                'description_en' => 'Permission to create new clubs',
                'value' => 'create-clubs',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Управление клубами',
                'title_kk' => 'Клубтарды басқару',
                'title_en' => 'Manage Clubs',
                'description_ru' => 'Разрешение на редактирование существующих клубов',
                'description_kk' => 'Қолданыстағы клубтарды өңдеу рұқсаты',
                'description_en' => 'Permission to edit existing clubs',
                'value' => 'manage-clubs',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Удаление клубов',
                'title_kk' => 'Клубтарды жою',
                'title_en' => 'Delete Clubs',
                'description_ru' => 'Разрешение на удаление клубов',
                'description_kk' => 'Клубтарды жою рұқсаты',
                'description_en' => 'Permission to delete clubs',
                'value' => 'delete-clubs',
                'is_system' => true,
            ],

            // Club Team Management Permissions
            [
                'title_ru' => 'Просмотр составов команд',
                'title_kk' => 'Команда құрамдарын көру',
                'title_en' => 'View Club Teams',
                'description_ru' => 'Разрешение на просмотр составов команд клубов',
                'description_kk' => 'Клуб командаларының құрамдарын көру рұқсаты',
                'description_en' => 'Permission to view club team compositions',
                'value' => 'view-club-teams',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Добавление участников в команды',
                'title_kk' => 'Командаларға қатысушыларды қосу',
                'title_en' => 'Create Club Teams',
                'description_ru' => 'Разрешение на добавление участников в команды клубов',
                'description_kk' => 'Клуб командаларына қатысушыларды қосу рұқсаты',
                'description_en' => 'Permission to add members to club teams',
                'value' => 'create-club-teams',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Управление составом команд',
                'title_kk' => 'Команда құрамдарын басқару',
                'title_en' => 'Manage Club Teams',
                'description_ru' => 'Разрешение на редактирование участников команд клубов',
                'description_kk' => 'Клуб командалары қатысушыларын өңдеу рұқсаты',
                'description_en' => 'Permission to edit club team members',
                'value' => 'manage-club-teams',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Удаление участников из команд',
                'title_kk' => 'Командалардан қатысушыларды жою',
                'title_en' => 'Delete Club Teams',
                'description_ru' => 'Разрешение на удаление участников из команд клубов',
                'description_kk' => 'Клуб командаларынан қатысушыларды жою рұқсаты',
                'description_en' => 'Permission to remove members from club teams',
                'value' => 'delete-club-teams',
                'is_system' => true,
            ],

            // Licence Management Permissions
            [
                'title_ru' => 'Просмотр лицензий',
                'title_kk' => 'Лицензияларды көру',
                'title_en' => 'View Licences',
                'description_ru' => 'Разрешение на просмотр списка лицензий',
                'description_kk' => 'Лицензиялар тізімін көру рұқсаты',
                'description_en' => 'Permission to view licences list',
                'value' => 'view-licences',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Создание лицензий',
                'title_kk' => 'Лицензияларды жасау',
                'title_en' => 'Create Licences',
                'description_ru' => 'Разрешение на создание новых лицензий',
                'description_kk' => 'Жаңа лицензияларды жасау рұқсаты',
                'description_en' => 'Permission to create new licences',
                'value' => 'create-licences',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Управление лицензиями',
                'title_kk' => 'Лицензияларды басқару',
                'title_en' => 'Manage Licences',
                'description_ru' => 'Разрешение на редактирование существующих лицензий',
                'description_kk' => 'Қолданыстағы лицензияларды өңдеу рұқсаты',
                'description_en' => 'Permission to edit existing licences',
                'value' => 'manage-licences',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Удаление лицензий',
                'title_kk' => 'Лицензияларды жою',
                'title_en' => 'Delete Licences',
                'description_ru' => 'Разрешение на удаление лицензий',
                'description_kk' => 'Лицензияларды жою рұқсаты',
                'description_en' => 'Permission to delete licences',
                'value' => 'delete-licences',
                'is_system' => true,
            ],

            // Licence Requirement Management Permissions
            [
                'title_ru' => 'Просмотр требований к лицензиям',
                'title_kk' => 'Лицензияларға қойылатын талаптарды көру',
                'title_en' => 'View Licence Requirements',
                'description_ru' => 'Разрешение на просмотр требований к лицензиям',
                'description_kk' => 'Лицензияларға қойылатын талаптарды көру рұқсаты',
                'description_en' => 'Permission to view licence requirements',
                'value' => 'view-licence-requirements',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Создание требований к лицензиям',
                'title_kk' => 'Лицензияларға қойылатын талаптарды жасау',
                'title_en' => 'Create Licence Requirements',
                'description_ru' => 'Разрешение на создание требований к лицензиям',
                'description_kk' => 'Лицензияларға қойылатын талаптарды жасау рұқсаты',
                'description_en' => 'Permission to create licence requirements',
                'value' => 'create-licence-requirements',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Управление требованиями к лицензиям',
                'title_kk' => 'Лицензияларға қойылатын талаптарды басқару',
                'title_en' => 'Manage Licence Requirements',
                'description_ru' => 'Разрешение на редактирование требований к лицензиям',
                'description_kk' => 'Лицензияларға қойылатын талаптарды өңдеу рұқсаты',
                'description_en' => 'Permission to edit licence requirements',
                'value' => 'manage-licence-requirements',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Удаление требований к лицензиям',
                'title_kk' => 'Лицензияларға қойылатын талаптарды жою',
                'title_en' => 'Delete Licence Requirements',
                'description_ru' => 'Разрешение на удаление требований к лицензиям',
                'description_kk' => 'Лицензияларға қойылатын талаптарды жою рұқсаты',
                'description_en' => 'Permission to delete licence requirements',
                'value' => 'delete-licence-requirements',
                'is_system' => true,
            ],
            // Application for License Permission
            [
                'title_ru' => 'Подача заявки на лицензию',
                'title_kk' => 'Лицензияға өтінім беру',
                'title_en' => 'Apply for License',
                'description_ru' => 'Разрешение на подачу заявок на получение лицензии',
                'description_kk' => 'Лицензия алу үшін өтінімдер беру рұқсаты',
                'description_en' => 'Permission to submit license applications',
                'value' => 'apply-for-license',
                'is_system' => true,
            ],

            // Licence Deadlines
            [
                'title_ru' => 'Просмотр дедлайнов лицензий',
                'title_kk' => 'Лицензиялардың мерзімдерін көру',
                'title_en' => 'View Licence Deadlines',
                'description_ru' => 'Разрешение на просмотр дедлайнов лицензий',
                'description_kk' => 'Лицензиялардың мерзімдерін көру рұқсаты',
                'description_en' => 'Permission to view licence deadlines',
                'value' => 'view-licence-deadlines',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Создание дедлайнов лицензий',
                'title_kk' => 'Лицензиялардың мерзімдерін құру',
                'title_en' => 'Create Licence Deadlines',
                'description_ru' => 'Разрешение на создание дедлайнов лицензий',
                'description_kk' => 'Лицензиялардың мерзімдерін құру рұқсаты',
                'description_en' => 'Permission to create licence deadlines',
                'value' => 'create-licence-deadlines',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Управление дедлайнами лицензий',
                'title_kk' => 'Лицензиялардың мерзімдерін басқару',
                'title_en' => 'Manage Licence Deadlines',
                'description_ru' => 'Разрешение на редактирование дедлайнов лицензий',
                'description_kk' => 'Лицензиялардың мерзімдерін өңдеу рұқсаты',
                'description_en' => 'Permission to edit licence deadlines',
                'value' => 'manage-licence-deadlines',
                'is_system' => true,
            ],
            [
                'title_ru' => 'Удаление дедлайнов лицензий',
                'title_kk' => 'Лицензиялардың мерзімдерін жою',
                'title_en' => 'Delete Licence Deadlines',
                'description_ru' => 'Разрешение на удаление дедлайнов лицензий',
                'description_kk' => 'Лицензиялардың мерзімдерін жою рұқсаты',
                'description_en' => 'Permission to delete licence deadlines',
                'value' => 'delete-licence-deadlines',
                'is_system' => true,
            ],
        ];

        foreach ($permissions as $permission) {
            Permission::updateOrCreate(
                ['value' => $permission['value']],
                $permission
            );
        }
    }
}
